//product types
export const GET_PRODUCTS = 'SET_PRODUCTS'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const CATEGORY_FAIL='CATEGORY_FAIL'
export const GET_IMAGES = 'SET_IMAGES'
export const SET_IMAGES_URL='SET_IMAGES_URL'
export const GET_CART='GET_CART'
export const GET_VARIETS='GET_VARIETS'
export const SET_FILTER='SET_FILTER'
//user types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAIL = 'UPDATE_FAIL'